/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-10-13 22:40:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.RegisteredC;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class payment_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/includes/CHeader.jsp", Long.valueOf(1728741968486L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Payment</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link href=\"../styles/payment.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../styles/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");


	
	String description = request.getParameter("description");
	String amt = request.getParameter("amt");
	String passengers = request.getParameter("passengers");
	String rental = request.getParameter("rental");
	String ftype = request.getParameter("ftype");
	String brand = request.getParameter("brand");
	String tradeName = request.getParameter("tradeName");
	String vd = request.getParameter("vid");
	
	


	HttpSession ses = request.getSession();
	
	ses.setAttribute("vid", vd);
	


	String pdate = (String)ses.getAttribute("pickup_date");
	String rdate = (String)ses.getAttribute("return_date");
	String paddress = (String)ses.getAttribute("paddress");
	String daddress = (String)ses.getAttribute("daddress");
	





	


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Book</title>\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"../styles/header.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--Header nav start-->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-body-tertiary p-0\">\r\n");
      out.write("        <div class=\"container-fluid bg-dark navbar-dark mb-0 p-3\">\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">Rent-ME!</a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link active hdr\" aria-current=\"page\" href=\"../RegisteredC/booking.jsp\">Home</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link active hdr\" href=\"RegisteredC/RegisteredProfile.jsp\">View profile</a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link active hdr\" href=\"RegisteredC/myR(refresh).jsp\">Dashboard</a>\r\n");
      out.write("              </li>\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("           \r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"mx-3\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-primary\" type=\"submit\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">Log-out</button>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("      <!--Header nav end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row m-0\">\r\n");
      out.write("            <div class=\"col-lg-7 pb-5 pe-lg-5\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-12 p-5\">\r\n");
      out.write("                        <img src=\"https://www.freepnglogos.com/uploads/honda-car-png/honda-car-upcoming-new-honda-cars-india-new-honda-3.png\"\r\n");
      out.write("                            alt=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"row m-0 bg-light\">\r\n");
      out.write("                        <div class=\"col-md-4 col-6 ps-30 pe-0 my-4\">\r\n");
      out.write("                            <p class=\"text-muted\">Transmission</p>\r\n");
      out.write("                            <p class=\"h5\">");
      out.print( amt );
      out.write("<span class=\"ps-1\"></span></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 col-6  ps-30 my-4\">\r\n");
      out.write("                            <p class=\"text-muted\">Passengers</p>\r\n");
      out.write("                            <p class=\"h5 m-0\">");
      out.print( passengers );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 col-6 ps-30 my-4\">\r\n");
      out.write("                            <p class=\"text-muted\">");
      out.print( ftype );
      out.write("</p>\r\n");
      out.write("                            <p class=\"h5 m-0\">Petrol</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-md-4 col-6 ps-30 my-4\">\r\n");
      out.write("                            <p class=\"text-muted\">Notes</p>\r\n");
      out.write("                            <p class=\"h5 m-0\">");
      out.print( description );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                       \r\n");
      out.write("  \r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-5 p-0 ps-lg-4\">\r\n");
      out.write("                <div class=\"row m-0\">\r\n");
      out.write("                    <div class=\"col-12 px-4\">\r\n");
      out.write("                        <div class=\"d-flex align-items-end mt-4 mb-2\">\r\n");
      out.write("                            <p class=\"h4 m-0\"><span class=\"pe-1\">");
      out.print( brand );
      out.write("</span><span class=\"pe-1\">");
      out.print( tradeName );
      out.write("</span>\r\n");
      out.write("                            </p>\r\n");
      out.write("                            <P class=\"ps-3 textmuted\">1L</P>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">Pickup date:</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\">");
      out.print( pdate );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">End date:</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign pe-1\"></span>");
      out.print( rdate );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">Pick-up location:</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\">");
      out.print( paddress );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">Destination Location:</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\"><span class=\"fas fa-dollar-sign px-1\"></span>");
      out.print( daddress );
      out.write("</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-2\">\r\n");
      out.write("                            <p class=\"textmuted\">Offers:</p>\r\n");
      out.write("                            <p class=\"fs-14 fw-bold\">0</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"d-flex justify-content-between mb-3\">\r\n");
      out.write("                            <p class=\"textmuted fw-bold\">Total</p>\r\n");
      out.write("                            <div class=\"d-flex align-text-top \">\r\n");
      out.write("                                <span class=\"fas fa-dollar-sign mt-1 pe-1 fs-14 \"></span>RS. <span class=\"h4\">");
      out.print( rental );
      out.write("</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Start Of Form -->\r\n");
      out.write("                    <form method = \"post\" action=\"../PaymentServlet\">\r\n");
      out.write("                    <div class=\"col-12 px-0\">\r\n");
      out.write("                        <div class=\"row bg-light m-0\">\r\n");
      out.write("                            <div class=\"col-12 px-4 my-4\">\r\n");
      out.write("                                <p class=\"fw-bold\">Payment detail</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 px-4\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"d-flex  mb-4\">\r\n");
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                    <span class=\"\">\r\n");
      out.write("                                        <p class=\"text-muted\">Card type</p>\r\n");
      out.write("                                        <label>Visa</label>\r\n");
      out.write("                                        <input class=\"\" type=\"radio\" value=\"Visa\" name=\"cardType\" required>\r\n");
      out.write("\r\n");
      out.write("                                        <label>Master</label>\r\n");
      out.write("                                        <input class=\"\" type=\"radio\" value=\"Master\" name=\"cardType\" required>\r\n");
      out.write("                                    </span>\r\n");
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                   \r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"d-flex  mb-4\">\r\n");
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                    <span class=\"\">\r\n");
      out.write("                                        <p class=\"text-muted\">Payment</p>\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" \r\n");
      out.write("                                            placeholder=\"RS.20000\" name=\"payment\"  value=\"");
      out.print( rental );
      out.write("\" readonly>\r\n");
      out.write("                                    </span>\r\n");
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                   \r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"d-flex  mb-4\">\r\n");
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("                                    <span class=\"\">\r\n");
      out.write("                                        <p class=\"text-muted\">Card number</p>\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" \r\n");
      out.write("                                            placeholder=\"1234 5678 9012 3456\" name=\"cardNo\" required>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\" w-100 d-flex flex-column align-items-end\">\r\n");
      out.write("                                        <p class=\"text-muted\">Expires</p>\r\n");
      out.write("                                        <input class=\"form-control2\" type=\"text\"  placeholder=\"MM/YYYY\" name=\"exp\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"d-flex mb-5\">\r\n");
      out.write("                                    <span class=\"me-5\">\r\n");
      out.write("                                        <p class=\"text-muted\">Cardholder name</p>\r\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" \r\n");
      out.write("                                            placeholder=\"Name\" name=\"chname\" required>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"w-100 d-flex flex-column align-items-end\">\r\n");
      out.write("                                        <p class=\"text-muted\">CVC</p>\r\n");
      out.write("                                        <input class=\"form-control3\" type=\"text\"  placeholder=\"XXX\" name=\"cvc\" required>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"row m-0\">\r\n");
      out.write("                            <div class=\"col-12  mb-4 p-0\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-primary\"  data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">Purchase\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Start of Modal -->\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <!-- Modal -->\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Do you wanna Book?</h1>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("        ...\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">No</button>\r\n");
      out.write("        <input type=\"submit\" class=\"btn btn-primary\" value=\"Yes\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <!-- End of Modal -->\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <!-- End form -->\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
