/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-10-16 03:31:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.vOwner;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".top-im{\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 70%;\r\n");
      out.write("    object-fit: contain;\r\n");
      out.write("    /*border-radius: 81% 19% 83% 17% / 34% 20% 80% 66% ;*/\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".quote1{\r\n");
      out.write("    position: relative;\r\n");
      out.write("    top: 6em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*<uniquifier>: Use a unique and descriptive class name\r\n");
      out.write(" <weight>: Use a value from 400 to 900*/\r\n");
      out.write("\r\n");
      out.write(".font1 {\r\n");
      out.write("  font-family: \"Playfair Display\", serif;\r\n");
      out.write("  font-optical-sizing: auto;\r\n");
      out.write("  font-weight: 600;\r\n");
      out.write("  font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card{\r\n");
      out.write("    width: 25%;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    margin: 20px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sec-2{\r\n");
      out.write("\r\n");
      out.write("    position: relative;\r\n");
      out.write("    top: -30px;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".card{\r\n");
      out.write("\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sec-1{\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".hdr:after {    \r\n");
      out.write("    background: none repeat scroll 0 0 transparent;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background: #d9dade;\r\n");
      out.write("    transition: width 0.3s ease 0s, left 0.3s ease 0s;\r\n");
      out.write("    width: 0;\r\n");
      out.write("  }\r\n");
      out.write("  .hdr:hover:after { \r\n");
      out.write("    width: 100%; \r\n");
      out.write("    left: 0; \r\n");
      out.write("  }\r\n");
      out.write("  li { \r\n");
      out.write("    display: table-cell; \r\n");
      out.write("    position: relative; \r\n");
      out.write("    padding: 20px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--Header nav start-->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-body-tertiary p-0\">\r\n");
      out.write("        <div class=\"container-fluid bg-dark navbar-dark mb-0 p-3\">\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">Rent-ME!</a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link active hdr\" aria-current=\"page\" href=\"../RegisteredC/booking.jsp\">Home</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link active hdr\" href=\"vOwner/register.jsp\"><button type=\"button\" class=\"btn btn-secondary\">Register</button></a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <form action=\"adminVehicle\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<button class=\"nav-link active hdr\" type=\"submit\">ALL Customers</button>\r\n");
      out.write("</form>\r\n");
      out.write("              </li>\r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("           \r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"mx-3\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-primary\" type=\"submit\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">Log-out</button>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("\r\n");
      out.write("      <!--Header nav end-->\r\n");
      out.write("<a href=\"vOwner/login.jsp\">\r\n");
      out.write("<button type=\"button\" class=\"btn btn-secondary\">My vehicles</button>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"vOwner/register.jsp\">\r\n");
      out.write("<button type=\"button\" class=\"btn btn-secondary\">Register</button>\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("<form action=\"adminVehicle\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<button type=\"submit\">ALL Customers</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- image/home -->\r\n");
      out.write("<div class=\"container-fluid  sec-1\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-9 mx-5\">\r\n");
      out.write("\r\n");
      out.write("            <h2 class=\"display-3 quote1 font1\">\r\n");
      out.write("                Rent the \r\n");
      out.write("                <span class=\"text-primary\">car</span> \r\n");
      out.write("                of your dream<br>\r\n");
      out.write("               <div class=\"text-start  w-50\"> <button class=\"btn btn-primary float\">Join us</button></div>\r\n");
      out.write("                </h2>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-20 m-0 p-0 opacity-100\">\r\n");
      out.write("        <img src=\"images/vincent-ghilione-bAEG-LbgQ7o-unsplash.jpg\" class=\"img-fluid top-im\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<!-- image/home end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
