/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-10-15 08:38:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class AdminDash_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"Admin/css/AdminStyle.css\">\r\n");
      out.write("    <!--  Fontawesome -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css\" integrity=\"sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\r\n");
      out.write("<title>Admin Dashboard</title>\r\n");
      out.write("<style>\r\n");
      out.write("        .card {\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card:hover {\r\n");
      out.write("            transform: scale(1.05);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card img {\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-body button {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            background-color: #28a745;\r\n");
      out.write("            text-shadow: 1px 1px 3px rgba(0, 0, 0, 0.5);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-body button:hover {\r\n");
      out.write("            background-color: rgba(0, 123, 255, 0.9);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-title {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-text {\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-deck {\r\n");
      out.write("            gap: 1.5rem;\r\n");
      out.write("        }\r\n");
      out.write("        .slidebar {\r\n");
      out.write("        	min-height: 100vh;\r\n");
      out.write("        	/* background-color: lightgray; */\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- Main container -->\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Slide bar -->\r\n");
      out.write("            <div class=\"col-sm-3 slidebar bg-light\">\r\n");
      out.write("                <h2 class=\"text-center\">Admin Dashboard</h2>\r\n");
      out.write("                <div class=\"slidebar-side-links\">\r\n");
      out.write("                    <a href=\"AdminDash.jsp\" class=\"d-flex justify-content-between\">\r\n");
      out.write("                        Dashboard\r\n");
      out.write("                        <i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                   \r\n");
      out.write("                    <div class=\"form-btn my-3\">\r\n");
      out.write("                        <form action=\"VehicleOwnerServlet\" method=\"post\">\r\n");
      out.write("                            <button type=\"submit\" class=\"click-btn btn d-flex justify-content-between align-items-center w-100\">\r\n");
      out.write("                                <span>Manage Vehicle Owners</span>\r\n");
      out.write("                                <i class=\"fa-solid fa-car\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("               \r\n");
      out.write("                    <div class=\"form-btn my-3\">\r\n");
      out.write("                        <form action=\"CusManageServlet\" method=\"post\">\r\n");
      out.write("                            <button type=\"submit\" class=\"click-btn btn d-flex justify-content-between align-items-center w-100\">\r\n");
      out.write("                                <span>Manager Customers</span>\r\n");
      out.write("                                <i class=\"fa-solid fa-people-robbery\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-btn my-3\">\r\n");
      out.write("                        <form action=\"ManagerDetailsServlet\" method=\"post\">\r\n");
      out.write("                            <button type=\"submit\" class=\"click-btn btn d-flex justify-content-between align-items-center w-100\">\r\n");
      out.write("                                <span>Manager Managers</span>\r\n");
      out.write("                                <i class=\"fa-solid fa-people-roof\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"d-flex justify-content-between\">\r\n");
      out.write("                        Reports\r\n");
      out.write("                        <i class=\"fa-solid fa-file-shield\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- horizontal line -->\r\n");
      out.write("                <hr class=\"horizontal-line\">\r\n");
      out.write("                <div class=\"ToDo-List text-center\">\r\n");
      out.write("                    <a href=\"#\" class=\"btn btn-secondary\">ToDo-List</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Body Content with Cards -->\r\n");
      out.write("			<div class=\"col-sm-9 p-3\">\r\n");
      out.write("			    \r\n");
      out.write("			    <div class=\"row mb-3\">\r\n");
      out.write("			        <!-- Customers Card -->\r\n");
      out.write("			        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("			            <div class=\"card\" style=\"width: 100%;\">\r\n");
      out.write("			               <!-- <img src=\"./images/customers.jpeg\" class=\"card-img-top\">  --> \r\n");
      out.write("			                <img src=\"https://th.bing.com/th/id/R.0e3b255eb522823e2f77e3058d2b6396?rik=T%2fPyjXz8VVQiFw&riu=http%3a%2f%2fcoolerinsights.com%2fwp-content%2fuploads%2f2013%2f10%2fThe-5-Levels-of-Customer-Engagement.jpg&ehk=Czo5NZeu1lxVL2wDn6S25NnASeJ%2bvOWV0O%2boNCBjkN8%3d&risl=&pid=ImgRaw&r=0\" class=\"card-img-top\">\r\n");
      out.write("			                <div class=\"card-body\">\r\n");
      out.write("			                    <h5 class=\"card-title\">Customers</h5>\r\n");
      out.write("			                    <p class=\"card-text\">Manage and view all customers of the platform.</p>\r\n");
      out.write("			                    <form action=\"CusManageServlet\" method=\"post\">\r\n");
      out.write("			                        <button type=\"submit\" class=\"btn w-100\">View All Customers</button>\r\n");
      out.write("			                    </form>\r\n");
      out.write("			                </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			\r\n");
      out.write("			        <!-- Vehicle Owners Card -->\r\n");
      out.write("			        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("			            <div class=\"card\" style=\"width: 100%;\">\r\n");
      out.write("			               <!--  <img src=\"./images/vehicleOwner.jpeg\" class=\"card-img-top\">  -->\r\n");
      out.write("			                <img src=\"https://th.bing.com/th/id/OIP.O5neAXRPXKfTVo0Cf9fcpAHaEK?w=324&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7\" class=\"card-img-top\">\r\n");
      out.write("			                <div class=\"card-body\">\r\n");
      out.write("			                    <h5 class=\"card-title\">Vehicle Owners</h5>\r\n");
      out.write("			                    <p class=\"card-text\">Manage and view all vehicle owners</p>\r\n");
      out.write("			                    <form action=\"VehicleOwnerServlet\" method=\"post\">\r\n");
      out.write("			                        <button type=\"submit\" class=\"btn w-100\">View All Vehicle Owners</button>\r\n");
      out.write("			                    </form>\r\n");
      out.write("			                </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			    </div>\r\n");
      out.write("			\r\n");
      out.write("			    \r\n");
      out.write("			    <div class=\"row\">\r\n");
      out.write("			        <!-- Ma	nagers Card -->\r\n");
      out.write("			        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("			            <div class=\"card\" style=\"width: 100%;\">\r\n");
      out.write("			                <img src=\"https://th.bing.com/th/id/OIP.RTbX_asli_ftt4h4hJOuzgHaD_?rs=1&pid=ImgDetMain\" class=\"card-img-top\">\r\n");
      out.write("			                <div class=\"card-body\">\r\n");
      out.write("			                    <h5 class=\"card-title\">Managers</h5>\r\n");
      out.write("			                    <p class=\"card-text\">Manage and view all managers</p>\r\n");
      out.write("			                    <form action=\"ManagerDetailsServlet\" method=\"post\">\r\n");
      out.write("			                        <button type=\"submit\" class=\"btn w-100\">View All Managers</button>\r\n");
      out.write("			                    </form>\r\n");
      out.write("			                </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("			\r\n");
      out.write("			        <!-- Vehicle Category Card -->\r\n");
      out.write("			        <div class=\"col-md-6 mb-3\">\r\n");
      out.write("			            <div class=\"card\" style=\"width: 100%;\">\r\n");
      out.write("			                <img src=\"https://www.mercedes-benz.com/content/dam/brandhub/vehicles/vehicle-overview/00-mercedes-benz-vehicles-passnger-cars-vans-2560x1440.cbv20230517105847.jpg/_jcr_content/renditions/mq7-original-aspect.jpeg\" class=\"card-img-top\">\r\n");
      out.write("			                <div class=\"card-body\">\r\n");
      out.write("			                    <h5 class=\"card-title\">Vehicle Categories</h5>\r\n");
      out.write("			                    <p class=\"card-text\">Manage and view all vehicle categories available for rental.</p>\r\n");
      out.write("			                    <form action=\"VcategoryDetailsServlet\" method=\"post\">\r\n");
      out.write("			                        <button type=\"submit\" class=\"btn w-100\">View All Vehicle Categories</button>\r\n");
      out.write("			                    </form>\r\n");
      out.write("			                </div>\r\n");
      out.write("			            </div>\r\n");
      out.write("			        </div>\r\n");
      out.write("    			</div>\r\n");
      out.write("			</div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("		\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
