/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.26
 * Generated at: 2024-10-13 11:06:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manager;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;

public final class Manger_0028offers_0029_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar", Long.valueOf(1728741541117L));
    _jspx_dependants.put("jar:file:/C:/Users/CHAMA%20COMPUTERS/Desktop/Vehicle_Rentel_System/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/VehicleRental1/WEB-INF/lib/jakarta.servlet.jsp.jstl-2.0.0.jar!/META-INF/c.tld", Long.valueOf(1602854172000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("     <!--links for bs 5 cdn-->\r\n");
      out.write("     <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("     <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("     <!--BS icon cdn-->\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css\">\r\n");
      out.write("    <title>Offers</title>\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("      \r\n");
      out.write("        .hdr:after {    \r\n");
      out.write("    background: none repeat scroll 0 0 transparent;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    display: block;\r\n");
      out.write("    height: 2px;\r\n");
      out.write("    left: 50%;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    background: #d9dade;\r\n");
      out.write("    transition: width 0.3s ease 0s, left 0.3s ease 0s;\r\n");
      out.write("    width: 0;\r\n");
      out.write("  }\r\n");
      out.write("  .hdr:hover:after { \r\n");
      out.write("    width: 100%; \r\n");
      out.write("    left: 0; \r\n");
      out.write("  }\r\n");
      out.write(" #ni { \r\n");
      out.write("    display: table-cell; \r\n");
      out.write("    position: relative; \r\n");
      out.write("    padding: 20px;\r\n");
      out.write("  }\r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"bg-dark\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<nav class=\"navbar navbar-expand-lg bg-body-tertiary p-0 mb-0\">\r\n");
      out.write("        <div class=\"container-fluid bg-dark navbar-dark pb-5 p-3\">\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">Rent-ME!</a>\r\n");
      out.write("          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0 me-auto mb-2 mb-lg-0 mx-auto\">\r\n");
      out.write("              <li class=\"nav-item p-2\" id =\"ni\">\r\n");
      out.write("                <a class=\"nav-link active hdr  text-white p-2\" aria-current=\"page\" href=\"ManagerDash.jsp\" >DashBoard</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item p-2\" id =\"ni\">\r\n");
      out.write("                <a class=\"nav-link active hdr  text-white p-2\" href=\"Manger(offers).jsp\" onclick=\"submitHiddenForm()\">Offers</a>\r\n");
      out.write("              </li>\r\n");
      out.write("\r\n");
      out.write("              <li class=\"nav-item p-2\" id =\"ni\">\r\n");
      out.write("                <a class=\"nav-link active hdr text-white p-2\" href=\"manager(bookings).jsp\">Bookings</a>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("             <div class=\"mx-3\">\r\n");
      out.write("              <img src=\" https://happytravel.viajes/wp-content/uploads/2020/04/146-1468479_my-profile-icon-blank-profile-picture-circle-hd-600x475.png\" alt=\"\" class=\"rounded-circle\" style=\"width: 32px;height: 32px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </nav>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row text-center my-4\">\r\n");
      out.write("            <div class=\"col-lg-4 \"><button  class=\"btn bg-secondary text-white p-5 border rounded-pill\" data-bs-toggle=\"modal\" data-bs-target=\"#addoffer\"><h3>+ADD OFFER</h3></button></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"conatainer\">\r\n");
      out.write("        <div class=\"row align-items-center justify-content-center\">\r\n");
      out.write("            <section id=\"pricing\" class=\"bg-dark text-light mt-5\">\r\n");
      out.write("                <div class=\"container-lg\">\r\n");
      out.write("                  <div class=\"text-center\">\r\n");
      out.write("                    <h2 class=\"pt-3\">Offer catagories</h2>\r\n");
      out.write("                    <p class=\"lead text-muted\">Available offer catogories..</p>\r\n");
      out.write("                  </div>\r\n");
      out.write("              \r\n");
      out.write("                  <div class=\"row my-5 g-0 align-items-center justify-content-center\">\r\n");
      out.write("                    <div class=\"col-8 col-lg-4 col-xl-3\">\r\n");
      out.write("                      <div class=\"card border-0\">\r\n");
      out.write("                        <div class=\"card-body text-center py-4 bg-dark text-light\">\r\n");
      out.write("                          <h4 class=\"card-title\">weekly offers</h4>\r\n");
      out.write("                          <p class=\"display-5 my-4 text-info fw-bold\">currently available</p><br>\r\n");
      out.write("                          <p class=\"display-4 text-white\">10</p>\r\n");
      out.write("                          <form action= \"ViewOffersCat\" method = \"post\">\r\n");
      out.write("                          <input type=\"hidden\" id=\"cat\" name=\"cato\" value=\"m\">\r\n");
      out.write("                          <button  class=\"btn btn-outline-info btn-lg mt-3\" onclick =\"disCat('w')\" type=\"submit\">\r\n");
      out.write("                            select\r\n");
      out.write("                          </button>\r\n");
      out.write("                          </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("              \r\n");
      out.write("                    <div class=\"col-9 col-lg-4\">\r\n");
      out.write("                      <div class=\"card border-info border-2\">\r\n");
      out.write("                        <div class=\"card-header text-center text-info bg-secondary \">FOR loyal customers</div>\r\n");
      out.write("                        <div class=\"card-body text-center py-5 bg-dark text-light\">\r\n");
      out.write("                          <h4 class=\"card-title\">offers for loyal customers</h4>\r\n");
      out.write("                          <p class=\"lead card-subtitle\">avilable offers</p><br>\r\n");
      out.write("                          <p class=\"display-4 text-white\">10</p>\r\n");
      out.write("                          <form action= \"ViewOffersCat\" method = \"post\">\r\n");
      out.write("                          <input type=\"hidden\" id=\"cat\" name=\"cato\" value=\"m\">\r\n");
      out.write("                          <button  class=\"btn btn-outline-info btn-lg mt-3\" onclick =\"disCat('l')\" type=\"submit\">\r\n");
      out.write("                            select\r\n");
      out.write("                          </button>\r\n");
      out.write("                          </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("              \r\n");
      out.write("                    <div class=\"col-8 col-lg-4 col-xl-3\">\r\n");
      out.write("                      <div class=\"card border-0\">\r\n");
      out.write("                        <div class=\"card-body text-center py-4 bg-dark text-light\">\r\n");
      out.write("                          <h4 class=\"card-title\">Monthly offers</h4>\r\n");
      out.write("                          <p class=\"lead card-subtitle\"></p><br>\r\n");
      out.write("                          <p class=\"display-5 my-4 text-info fw-bold\">currently available</p>\r\n");
      out.write("                          <p class=\"display-4 text-white\">10</p>\r\n");
      out.write("                          <form action= \"ViewOffersCat\" method = \"post\">\r\n");
      out.write("                          <input type=\"hidden\" id=\"cat\" name=\"cato\" value=\"m\">\r\n");
      out.write("                          <button  class=\"btn btn-outline-info btn-lg mt-3\" onclick =\"disCat('m')\" type=\"submit\">\r\n");
      out.write("                            select\r\n");
      out.write("                          </button>\r\n");
      out.write("                          </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              \r\n");
      out.write("                </div><!-- end container -->\r\n");
      out.write("              </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" 	\r\n");
      out.write("	\r\n");
      out.write("    <div class=\"container mb-5\">\r\n");
      out.write("        <div class=\"row align-items-center justify-content-center text-center\">\r\n");
      out.write("          \r\n");
      out.write("           \r\n");
      out.write("   <form action=\"../ViewOffers\"  id=\"hiddenForm\" method =\"get\">\r\n");
      out.write("       <button type=\"submit\" class=\"btn btn-info p-2\">All offers</button>\r\n");
      out.write("    </form>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("     <div class=\"container mt-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  \r\n");
      out.write("		<!-- Footer -->\r\n");
      out.write("<footer class=\"text-center text-lg-start bg-dark text-white\">\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("    <section class=\"d-flex justify-content-center justify-content-lg-between p-4 border-bottom\">\r\n");
      out.write("      <!-- Left -->\r\n");
      out.write("      <div class=\"me-5 d-none d-lg-block\">\r\n");
      out.write("        <span>Get connected with us on social networks:</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Left -->\r\n");
      out.write("  \r\n");
      out.write("      <!-- Right -->\r\n");
      out.write("      <div>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset\">\r\n");
      out.write("          <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset\">\r\n");
      out.write("          <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset\">\r\n");
      out.write("          <i class=\"fab fa-google\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset\">\r\n");
      out.write("          <i class=\"fab fa-instagram\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset\">\r\n");
      out.write("          <i class=\"fab fa-linkedin\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"\" class=\"me-4 text-reset\">\r\n");
      out.write("          <i class=\"fab fa-github\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Right -->\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section: Social media -->\r\n");
      out.write("  \r\n");
      out.write("    <!-- Section: Links  -->\r\n");
      out.write("    <section class=\"\">\r\n");
      out.write("      <div class=\"container text-center text-md-start mt-5\">\r\n");
      out.write("        <!-- Grid row -->\r\n");
      out.write("        <div class=\"row mt-3\">\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("          <div class=\"col-md-3 col-lg-4 col-xl-3 mx-auto mb-4\">\r\n");
      out.write("            <!-- Content -->\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("              <i class=\"fas fa-gem me-3\"></i>RentME!\r\n");
      out.write("            </h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              Here you can use rows and columns to organize your footer content. Lorem ipsum\r\n");
      out.write("              dolor sit amet, consectetur adipisicing elit.\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("  \r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("          <div class=\"col-md-2 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <!-- Links -->\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("              Products\r\n");
      out.write("            </h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#!\" class=\"text-reset\">Angular</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#!\" class=\"text-reset\">React</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#!\" class=\"text-reset\">Vue</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#!\" class=\"text-reset\">Laravel</a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("  \r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("          <div class=\"col-md-3 col-lg-2 col-xl-2 mx-auto mb-4\">\r\n");
      out.write("            <!-- Links -->\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">\r\n");
      out.write("              Useful links\r\n");
      out.write("            </h6>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#!\" class=\"text-reset\">Pricing</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#!\" class=\"text-reset\">Settings</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#!\" class=\"text-reset\">Orders</a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <a href=\"#!\" class=\"text-reset\">Help</a>\r\n");
      out.write("            </p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("  \r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("          <div class=\"col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4\">\r\n");
      out.write("            <!-- Links -->\r\n");
      out.write("            <h6 class=\"text-uppercase fw-bold mb-4\">Contact</h6>\r\n");
      out.write("            <p><i class=\"fas fa-home me-3\"></i> 45/2, Batharamulla, Sri Lanka</p>\r\n");
      out.write("            <p>\r\n");
      out.write("              <i class=\"fas fa-envelope me-3\"></i>\r\n");
      out.write("              yyy@example.com\r\n");
      out.write("            </p>\r\n");
      out.write("            <p><i class=\"fas fa-phone me-3\"></i> + 01 234 567 88</p>\r\n");
      out.write("            <p><i class=\"fas fa-print me-3\"></i> + 01 234 567 89</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Grid column -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Grid row -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <!-- Section: Links  -->\r\n");
      out.write("  \r\n");
      out.write("    <!-- Copyright -->\r\n");
      out.write("    <div class=\"text-center p-4\" style=\"background-color: rgba(0, 0, 0, 0.05);\">\r\n");
      out.write("      © 2024 Copyright:\r\n");
      out.write("      <a class=\"text-reset fw-bold\" href=\"#\">RentME!</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Copyright -->\r\n");
      out.write("  </footer>\r\n");
      out.write("  <!-- Footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("    <!--add offer modal-->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modal fade\" id=\"addoffer\"  data-bs-backdrop=\"static\" tabindex=\"-1\" aria-labelledby=\"modal-title\" aria-hidden=\"true\">\r\n");
      out.write("      <div class=\"modal-dialog\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"modal-header bg-dark\">\r\n");
      out.write("            <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-body bg-dark text-light\">\r\n");
      out.write("              <h2>Add offer</h2>\r\n");
      out.write("            <form action=\"../AddOfferServlet\" method=\"post\">\r\n");
      out.write("              \r\n");
      out.write("              <label for=\"modal-email\" class=\"form-label\">offer name</label>\r\n");
      out.write("              <input type=\"text\" class=\"form-control bg-dark text-light\" id=\"ofname\" name=\"ofname\">\r\n");
      out.write("    \r\n");
      out.write("              <label for=\"cat\" class=\"form-label\">catogory</label>\r\n");
      out.write("              <div class=\"dropdown\">\r\n");
      out.write("                  <button class=\"btn btn-secondary dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("                    catagory\r\n");
      out.write("                  </button>\r\n");
      out.write("                  <ul class=\"dropdown-menu bg-dark text-light\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("                    <li><a class=\"dropdown-item text-light\" href=\"#\" onclick=\"selectCategory('weekly')\">Weekly Offer</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item text-light\" href=\"#\" onclick=\"selectCategory('loyal_cust')\">Loyal Customer Offer</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item text-light\" href=\"#\" onclick=\"selectCategory('monthly')\">Monthly Offer</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <input type=\"hidden\" name=\"category\" id=\"categoryInput\">\r\n");
      out.write("              \r\n");
      out.write("              <label for=\"description\" class=\"form-label mt-2 \">Description</label>\r\n");
      out.write("              <textarea name=\"ofdescription\" id=\"ofdescription\" class=\"form-control bg-dark text-light\">Breif description about the offer</textarea>\r\n");
      out.write("  \r\n");
      out.write("              <label for=\"price\" class=\"form-label mt-2 fw-bold\">validity</label><br>\r\n");
      out.write("              start date: <br><br>\r\n");
      out.write("              <input type=\"date\" class=\"form-control bg-dark text-light\" id=\"ofstdate\" name=\"ofstdate\" ><br>\r\n");
      out.write("              End date: <br><br>\r\n");
      out.write("              <input type=\"date\" class=\"form-control bg-dark text-light\" id=\"ofendate\" name=\"ofendate\" >\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <input type=\"submit\" value=\"Add\" class=\"btn btn-success\">\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!--  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	-->\r\n");
      out.write("	\r\n");
      out.write("    <script>\r\n");
      out.write("      function selectCategory(category) {\r\n");
      out.write("        document.getElementById('categoryInput').value = category;\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    function disCat(c){\r\n");
      out.write("    	document.getElementById(\"cat\").value = c;\r\n");
      out.write("    }\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("	function confirmDelete() {\r\n");
      out.write("    return confirm(\"Are you sure you want to delete this offer?\");\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("        function submitHiddenForm() {\r\n");
      out.write("            document.getElementById('hiddenForm').submit();\r\n");
      out.write("        }\r\n");
      out.write("        </script>   \r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /manager/Manger(offers).jsp(168,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("offer");
      // /manager/Manger(offers).jsp(168,12) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/manager/Manger(offers).jsp(168,12) '${offers}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${offers}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                <div class=\"col-md-4\">\r\n");
            out.write("                    <div class=\"card bg-dark text-light mb-4\" style=\"width: 18rem; border-width: 10px;\">\r\n");
            out.write("                        <div class=\"card-body border-white\">\r\n");
            out.write("                            <h5 class=\"card-title display-5\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.offerName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h5>\r\n");
            out.write("                            <p class=\"card-text\">\r\n");
            out.write("                                <div class=\"t\">Category: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.category}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                                <div class=\"t\">Start Date: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.ofstdate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                                <div class=\"t\">End Date: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.ofendate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                                <div class=\"t\">Description: ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                            </p>\r\n");
            out.write("                            <a href=\"manager/OfferUpdate.jsp?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&name=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.offerName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&cat=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.category}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&std=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.ofstdate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&des=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn btn-info mt-4\" >Edit</a>\r\n");
            out.write("                            <a href=\"DeleteOfferServlet?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${offer.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" onclick=\"return confirmDelete()\" class=\"btn btn-warning mt-4 \">Delete</a>\r\n");
            out.write("                        </div>\r\n");
            out.write("                    </div>\r\n");
            out.write("                </div>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
